apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vaid-app-project
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'