apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-app-project-set
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: app-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-app-project'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/rmiguelito/ocm-argocd-hub-spoke.git
        targetRevision: HEAD
        path: appproject-manifest
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
